<?xml version="1.0" encoding="utf-8"?><Database Name="Tweets" Class="tweetObjDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Tweets.mdf;Integrated Security=True" SettingsObjectName="theTrumpButton.Properties.Settings" SettingsPropertyName="TweetsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TweetFaves" Member="TweetFaves">
    <Type Name="TweetFave">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateTweeted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="tweetBody" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="tweetID" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>